# Generated by Django 4.1.2 on 2024-01-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_userprofile_profile"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="address",),
        migrations.RemoveField(model_name="profile", name="age",),
        migrations.RemoveField(model_name="profile", name="contact_number",),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="profile_pics/"
            ),
        ),
    ]
